# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin 
        server-id: sonatype-nexus-staging
        server-username: ${{ secrets.OSSRH_USER }}
        server-password: ${{ secrets.OSSRH_PASSWORD }}
        gpg-passphrase:  ${{ secrets.GPG_PASSWORD }}

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
